{pkgs}: {
  deps = [
    pkgs.python313Packages.josepy
    pkgs.python312Packages.joblib
    pkgs.python313Packages.pywavefront
    pkgs.python312Packages.pyzstd
    pkgs.python313Packages.pyrituals
    pkgs.python312Packages.pyiqvia
    pkgs.python313Packages.pyformlang
    pkgs.python313Packages.pyreadstat
    pkgs.pywal16
    pkgs.python312Packages.python-ulid
    pkgs.watcherclient
    pkgs.pysqlrecon
    pkgs.python312Packages.pychannels
    pkgs.python312Packages.pytest-services
    pkgs.python313Packages.pyweatherflowudp
    pkgs.python313Packages.pylutron-caseta
    pkgs.python313Packages.pydantic-extra-types
    pkgs.python312Packages.pypdf3
    pkgs.python312Packages.pyramid-mako
    pkgs.python313Packages.pyseries
    pkgs.python313Packages.pymbolic
    pkgs.python313Packages.pyfaidx
    pkgs.texlivePackages.pygmentex
    pkgs.python312Packages.pytimeparse
    pkgs.python313Packages.python-docs-theme
    pkgs.python312Packages.py-eth-sig-utils
    pkgs.python313Packages.pytest-grpc
    pkgs.emacsPackages.python-environment
    pkgs.python312Packages.reprshed
    pkgs.python313Packages.pyinputevent
    pkgs.haskellPackages.PyF
    pkgs.python312Packages.pywavefront
    pkgs.rPackages.hydrostats
    pkgs.liferea
    pkgs.glasstty-ttf
    pkgs.rPackages.org_Rn_eg_db
    pkgs.rPackages.SimSurvey
    pkgs.rPackages.waspr
    pkgs.rPackages.ShinyItemAnalysis
    pkgs.haskellPackages.warp-static
    pkgs.rPackages.stylo
    pkgs.rPackages.measures
    pkgs.gatling
    pkgs.python312Packages.cleanlab
    pkgs.rPackages.sensitivity2x2xk
    pkgs.gomuks
    pkgs.python312Packages.linuxpy
    pkgs.rPackages.compicc
    pkgs.emacsPackages.laguna-theme
    pkgs.moosefs
    pkgs.rPackages.WLasso
    pkgs.emacsPackages.avy-zap
    pkgs.libsForQt5.shelf
    pkgs.perl540Packages.DateTimeFormatDateParse
    pkgs.rPackages.tablerDash
    pkgs.cosmic-comp
    pkgs.rrsync
    pkgs.xscreensaver
    pkgs.rPackages.VFS
    pkgs.typstPackages.cheda-seu-thesis_0_3_3
  ];
}
